### ISSUE TITLE
FR: add hyperlink to help

### ISSUE THREAD

**Issue by olivroy** [moodymudskipper/opt#8]
Hi,

I was wondering if it would be possible to add cli in Suggests.

If cli is installed, you could provide hyperlinks to help topics.

For example for readxl.
```r
opt$readxl$readxl.show_progress
Call `opt$readxl$readxl.show_progress()` to get and `opt$readxl$readxl.show_progress(value)` to set.
Try the following topic(s) for help on this option:
help("readxl_progress", "readxl")
This option is used by : `readxl::readxl_progress()`
```
if cli is installed, `help("readxl_progress", "readxl")` could be replaced by `cli::cli_bullets("{.help readxl::readxl_progress}")` which displays a hyperlink in the console (in RStudio) !, otherwise would not changed

For more details on cli hyperlinks https://cli.r-lib.org/reference/links.html

Thanks!

**Comment by moodymudskipper** [comment]
This is a great idea, thanks

**Comment by olivroy** [comment]
I don't know if your comment on r-lib/cli#598 was related to this.

But the issue was specifically about the {.run } hyperlinks {.fn} {.fun} {.help} can refer to base functions (as long as you put {.help base::fn}

**Comment by moodymudskipper** [comment]
Thanks, indeed I don't need this to link to the doc, but I wanted to also have hyperlinks to view the function code by clicking on the last line.

**Comment by moodymudskipper** [comment]
Thanks for the FR, this seems to improve the experience sensibly.

* We have hyperlinks to the doc
* We have hyperlinks to view functions, using a helper wrapper to View, documented with keywords internal because it had to be exported unfortunately
* I didn't change what I print because 
  * I find the `?pkg::topic` idiom confusing since topics and functions are often but not always the same
  * It differentiates better hyperlinks to doc and functions
  * It's less awkward with non syntactic topics

**Comment by olivroy** [comment]
Oh yes,  it is nice!
thanks!
